services:
  app-web:
    container_name: app-web
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    volumes:
      - ./app-web/:/app
    ports:
      - "8001:8000"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=localhost,10.6.80.*,10.6.89.*,microservice1
  app-web2:
    container_name: app-web2
    build:
      context: ./docker/php
      dockerfile: Dockerfile
#      args:
#        http_proxy: ${http_proxy}
#        https_proxy: ${https_proxy}
    volumes:
      - ./app-web2/:/app
    ports:
      - "8002:8000"
#    environment:
      #- http_proxy=${http_proxy}
      #- https_proxy=${https_proxy}
      #- no_proxy=localhost,10.6.80.*,10.6.89.*,microservice1
  microservice-symfony:
    container_name: microservice-symfony
    build:
      context: ./docker/symfony
      dockerfile: Dockerfile
#      args:
#        http_proxy: ${http_proxy}
#        https_proxy: ${https_proxy}
    volumes:
      - ./microservice-symfony/:/app
    ports:
      - "8003:8000"
#    environment:
      #- http_proxy=${http_proxy}
      #- https_proxy=${https_proxy}
#      - no_proxy=localhost,10.6.80.*,10.6.89.*,microservice-php
  microservice-php:
    container_name: microservice-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
#      args:
#        http_proxy: ${http_proxy}
#        https_proxy: ${https_proxy}
    volumes:
      - ./microservice-php/:/app
#    environment:
      #- http_proxy=${http_proxy}
      #- https_proxy=${https_proxy}
#      - no_proxy=localhost,10.6.80.*,10.6.89.*
  app-gestao-om:
    container_name: app-gestao-om
    build:
      context: ./docker/symfony
      dockerfile: Dockerfile
#      args:
#        http_proxy: ${http_proxy}
#        https_proxy: ${https_proxy}
    volumes:
      - ./app-gestao-om/:/app
    ports:
      - "8004:8000"
#    environment:
      #- http_proxy=${http_proxy}
      #- https_proxy=${https_proxy}
#      - no_proxy=localhost,10.6.80.*,10.6.89.*,microservice-php
  app-gestao-usuario:
    container_name: app-gestao-usuario
    build:
      context: ./docker/symfony
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    volumes:
      - ./app-gestao-usuario/:/app
    ports:
      - "8005:8000"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=localhost,10.6.80.*,10.6.89.*
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
  postgres_symfony:
    image: postgres:16
    container_name: postgres_symfony
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: symfony_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  keycloak_data:
  postgres_data: